CC=gcc
CFLAGS= -std=c11 -Wall -Wextra -Werror -pedantic -g

unary: unary.c
	$(CC) $(CFLAGS) -o unary unary.c

bitflip: bitflip.c
	$(CC) $(CFLAGS) -o bitflip bitflip.c

badd: badd.c
	$(CC) $(CFLAGS) -o badd badd.c